/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AkGithubFill: typeof import('@kalimahapps/vue-icons/ak')['AkGithubFill']
    CoMoon: typeof import('@kalimahapps/vue-icons/co')['CoMoon']
    MdOutlinedWbSunny: typeof import('@kalimahapps/vue-icons/md')['MdOutlinedWbSunny']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
